#!/usr/bin/env python3
"""Regenerates src/shortener/tracking_params.py from AdGuard's URL Tracking filter.

Run: python3 tools/refresh_tracking_params.py

Takes only the globally-scoped `$removeparam` rules. AdGuard's domain-scoped
rules are deliberately skipped: they exist because those names (ref, tag,
source, pid, c) are ordinary parameters off their own site, and applying them
everywhere would break destinations.
"""

import io
import os
import re
import subprocess
import sys

SOURCE = ("https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/"
          "master/filters/filter_17_TrackParam/filter.txt")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   "..", "src", "shortener", "tracking_params.py")

# names we refuse to take from upstream however they are scoped, because a
# redirect that loses them lands somewhere other than what was pasted
NEVER = frozenset([
  "url", "u", "redirect", "redirect_uri", "return", "return_url", "next",
  "continue", "callback", "code", "state", "token", "q", "query", "search",
  "id", "page", "lang", "locale", "sort", "filter", "type", "category",
])


def fetch(url):
  # curl rather than urllib: the python here ships without a CA bundle
  out = subprocess.run(["curl", "-sSLf", "--max-time", "30", url],
                       capture_output=True)
  if out.returncode:
    sys.exit("fetch failed: " + out.stderr.decode("utf-8", "replace").strip())
  return out.stdout.decode("utf-8", "replace")


def global_names(text):
  """Plain param names from rules with no domain scope and no URL pattern."""
  names = set()
  for line in text.splitlines():
    line = line.strip()
    if not line or line.startswith(("!", "@@")) or "removeparam=" not in line:
      continue
    left, _, opts = line.partition("$")
    if left not in ("", "*"):
      continue
    if re.search(r"(?<!~)domain=", opts):
      continue
    value = re.search(r"removeparam=([^,]+)", opts).group(1).strip()
    # a parameter name cannot hold these; anything carrying one is a regex or
    # wildcard rule that this plain-name parser has no business taking
    if value.startswith(("/", "~")) or any(ch in value for ch in "=*/^|"):
      continue
    names.add(value.lower())
  return names


def main():
  names = sorted(global_names(fetch(SOURCE)) - NEVER)
  if len(names) < 200:
    sys.exit("refusing to write: only %d names parsed, upstream format "
             "probably changed" % len(names))

  body = ["\"\"\"Generated by tools/refresh_tracking_params.py. Do not edit.",
          "",
          "Source: AdGuard URL Tracking filter (filter_17_TrackParam),",
          "globally-scoped $removeparam rules only.",
          "\"\"\"", "", "ADGUARD_GLOBAL = frozenset(["]
  line = " "
  for n in names:
    item = ' "%s",' % n
    if len(line) + len(item) > 78:
      body.append(line)
      line = " "
    line += item
  body.append(line)
  body.append("])")
  io.open(OUT, "w", encoding="utf-8").write("\n".join(body) + "\n")
  print("wrote %s with %d names" % (os.path.normpath(OUT), len(names)))


if __name__ == "__main__":
  main()
