"""Strips tracking and referral parameters out of a URL.

Three layers, because no single source is enough. Checked against Brave,
AdGuard and ClearURLs: none of them carry fb_cid, fb_asid, fb_aid or most of
the AppsFlyer af_ family, so a maintained list alone would still leak.

1. tracking_params.ADGUARD_GLOBAL - the long tail, regenerated by
   tools/refresh_tracking_params.py.
2. TRACKING_PREFIXES - whole families, so a new member needs no list update.
   This is what catches the names the upstream lists miss.
3. AMBIGUOUS - names that are only trackers in the company of other ad
   parameters. Brave does the same thing in kConditionalQueryStringTrackers.

Stdlib only, so it imports in a plain python3 without boto3 or AWS env vars.
"""

from urllib.parse import unquote_plus, urlsplit, urlunsplit

from tracking_params import ADGUARD_GLOBAL

# whole families, matched on the prefix, so new members need no list update
TRACKING_PREFIXES = (
  "utm_",       # includes utm_id and the ga4 additions the reference list omits
  "af_",        # appsflyer
  "fb_",        # meta ads: fb_cid, fb_asid, fb_aid
  "pk_",        # piwik
  "mtm_",       # matomo
  "hsa_",       # hubspot ads
  "_branch_",   # branch.io
)

TRACKING_PARAMS = frozenset([
  # social
  "fbclid", "igshid", "ttclid", "tiktok_r", "li_fat_id", "mkt_tok", "trk",
  "twclid", "rdt_cid", "epik", "mibextid",
  "fb_action_ids", "fb_action_types", "fb_ref", "fb_source",
  # ad platforms
  "gclid", "yclid", "dclid", "msclkid", "gad_source", "gad_campaignid",
  "gbraid", "wbraid", "gclsrc", "_gl", "matchtype", "campaign_id", "ad_id",
  "adgroup", "adposition", "s_kwcid", "ef_id",
  # affiliate and referral
  "ref", "referral", "referrer", "affiliate_id", "afid", "click_id",
  "clickid", "subid", "sub_id", "partner_id", "sr_share", "irclickid",
  "ref_src", "ref_url",
  # amazon
  "tag", "linkcode", "linkid", "ascsubtag", "camp", "creative",
  "pd_rd_i", "pd_rd_r", "pd_rd_w", "pd_rd_wg",
  # email and newsletter
  "ck_subscriber_id", "mc_cid", "mc_eid", "_hsenc", "_hsmi",
  "vero_id", "vero_conv", "oly_anon_id", "oly_enc_id",
  # analytics and generic
  "sthash", "source", "sourceid", "campaign", "_bhlid", "_openstat",
  "spm", "scm", "ncid", "cmpid", "icid", "ito",
])

# ordinary parameters that ad networks reuse: pid is usually a product id, c is
# about as generic as a name gets, placement is a real field on job boards.
# AdGuard only strips these per-domain for the same reason. They count as
# tracking here only when the query also carries an unmistakable ad parameter.
AMBIGUOUS = frozenset(["pid", "c", "placement"])

AD_CONTEXT_PREFIXES = ("af_", "fb_", "utm_")
AD_CONTEXT_PARAMS = frozenset([
  "gclid", "fbclid", "msclkid", "ttclid", "twclid", "yclid", "dclid",
  "gbraid", "wbraid", "srsltid", "igshid", "rdt_cid", "epik", "irclickid",
])


def _has_ad_context(keys):
  return any(k.startswith(AD_CONTEXT_PREFIXES) or k in AD_CONTEXT_PARAMS
             for k in keys)


def clean_url(url):
  """Return (cleaned_url, removed_keys). Unchanged input if nothing matched."""
  if not url:
    return url, []

  parts = urlsplit(url)
  if parts.scheme not in ("http", "https") or not parts.query:
    return url, []

  # split the raw query rather than parse_qsl/urlencode, so surviving params
  # keep their original percent-encoding
  segments = [s for s in parts.query.split("&") if s]
  keys = [unquote_plus(s.split("=", 1)[0]) for s in segments]
  lowered_keys = [k.lower() for k in keys]
  ad_context = _has_ad_context(lowered_keys)

  kept = []
  removed = []
  for segment, key, lowered in zip(segments, keys, lowered_keys):
    if (lowered in TRACKING_PARAMS
        or lowered in ADGUARD_GLOBAL
        or lowered.startswith(TRACKING_PREFIXES)
        or (ad_context and lowered in AMBIGUOUS)):
      removed.append(key)
    else:
      kept.append(segment)

  if not removed:
    return url, []

  return urlunsplit((parts.scheme, parts.netloc, parts.path,
                     "&".join(kept), parts.fragment)), removed
